replicaCount: 2

image:
  repository: 254185428277.dkr.ecr.us-east-1.amazonaws.com/ardocd-deployment
  tag: v13
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
