apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: deployment
  labels:
    app: grade-submission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-submission
  template:
    metadata:
      labels:
        app: grade-submission
    spec:
      containers:
      - name: grade-submission-api
        image: 254185428277.dkr.ecr.us-east-1.amazonaws.com/ardocd-deployment:v18
        ports:
          - containerPort: 3000
